USE PROJECTS;

SELECT *
FROM HR;

-- RENAMING THE ID COLUMN 

ALTER TABLE HR
CHANGE COLUMN ï»¿id Emp_id varchar (20) NULL;

DESCRIBE hr;

SELECT BIRTHDATE 
FROM HR;

SET SQL_SAFE_UPDATES = 0;

-- SETTING THE DATE FORMAT, MAKING IT UNIVOR "-" SEPARATED VALUES

UPDATE HR
SET BIRTHDATE = CASE
    WHEN BIRTHDATE LIKE '%/%' THEN DATE_FORMAT(STR_TO_DATE(BIRTHDATE, '%m/%d/%Y'), '%Y-%m-%d')
    WHEN BIRTHDATE LIKE '%-%' THEN DATE_FORMAT(STR_TO_DATE(BIRTHDATE, '%m-%d-%Y'), '%Y-%m-%d')
    ELSE NULL
END;

-- CHECKING IF THE BIRTHDATE IS UPDATED 

SELECT BIRTHDATE 
FROM HR;

-- CHANGING THE BIRTHDATE COLUMN FROM DATA TYPE "TEXT" TO "DATE"

ALTER TABLE HR
MODIFY COLUMN BIRTHDATE DATE;

DESCRIBE HR;

UPDATE HR
SET HIRE_DATE = CASE
    WHEN HIRE_DATE LIKE '%/%' THEN DATE_FORMAT(STR_TO_DATE(HIRE_DATE, '%m/%d/%Y'), '%Y-%m-%d')
    WHEN HIRE_DATE LIKE '%-%' THEN DATE_FORMAT(STR_TO_DATE(HIRE_DATE, '%m-%d-%Y'), '%Y-%m-%d')
    ELSE NULL
END;

ALTER TABLE HR
MODIFY COLUMN HIRE_DATE DATE;

-- REMOVING THE TIME-STUMP FROM "TERMDATE"

UPDATE HR
SET TERMDATE = DATE(STR_TO_DATE(TERMDATE, '%Y-%m-%d %H:%i:%s UTC'))
WHERE TERMDATE IS NOT NULL AND TERMDATE != '';

ALTER TABLE HR
MODIFY COLUMN TERMDATE DATE;

DESCRIBE HR;

-- FIND OUTLIERS IN OUR DATA 

ALTER TABLE HR
ADD COLUMN AGE INT;

SELECT *
FROM HR;

UPDATE HR
SET AGE = timestampdiff(YEAR, BIRTHDATE, CURDATE());

SELECT BIRTHDATE, AGE FROM HR;

SELECT 
	MIN(AGE) AS YOUNGEST,
	MAX(AGE) AS OLDEST
FROM HR;

SELECT COUNT(*)
FROM HR
WHERE AGE < 18;

-- QUESTIONS

-- 1. WHAT IS THE GENDER BREAKDOWN OF EMPLOYEES IN THE COMPANY?
SELECT GENDER, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY GENDER; 

-- WHAT IS THE RACE/ETHNICITY BREAKDOWN OF EMPLOYEES IN THE COMPANY?
SELECT RACE, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY RACE
ORDER BY COUNT(*) DESC;

-- 2. WHAT IS THE AGE DISTRIBUTION OF EMPLOYEES IN THE COMPANY?
SELECT 
MIN(AGE) AS YOUNGEST,
MAX(AGE) AS OLDEST
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL;

-- CREATING AGE GROUP TO ANSWER THE QUESTION

SELECT 
	CASE
		WHEN AGE >= 18 AND AGE <= 24 THEN '18-24'
        WHEN AGE >= 25 AND AGE <= 34 THEN '25-34'
        WHEN AGE >= 35 AND AGE <= 44 THEN '35-44'
        WHEN AGE >= 45 AND AGE <= 54 THEN '45-54'
        WHEN AGE >= 55 AND AGE <= 64 THEN '55-64'
        ELSE '65+'
	END AS AGE_GROUP,
    COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP;

-- 3. HOW THE GNEDER IS DISTRIBUTED AMONG THE AGE_GROUP
SELECT 
	CASE
		WHEN AGE >= 18 AND AGE <= 24 THEN '18-24'
        WHEN AGE >= 25 AND AGE <= 34 THEN '25-34'
        WHEN AGE >= 35 AND AGE <= 44 THEN '35-44'
        WHEN AGE >= 45 AND AGE <= 54 THEN '45-54'
        WHEN AGE >= 55 AND AGE <= 64 THEN '55-64'
        ELSE '65+'
	END AS AGE_GROUP, GENDER,
    COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY AGE_GROUP, GENDER
ORDER BY AGE_GROUP, GENDER;

-- 4. HOW MANY EMPLOYEES WORK AT HEADQUARTERS VERSUS REMOTE LOCATIONS?

SELECT LOCATION, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY LOCATION;

-- 5. WHAT IS THE AVERAGE LENGTH OF EMPLOYMENT FOR EMPLOYEES WHO HAVE BEEN TERMINATED?

SELECT 
	ROUND(AVG(datediff(TERMDATE, HIRE_DATE))/365,0) AS AVG_LENGTH_EMPLOYMENT 
    FROM HR
    WHERE TERMDATE <= CURDATE() AND TERMDATE IS NOT NULL AND AGE <= 18;

-- 6. HOW DOES THE GENDER DISTRIBUTION VARY ACROSS DEPARTMENTS AND JOB TITLES?
SELECT DEPARTMENT, GENDER, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY DEPARTMENT, GENDER
ORDER BY DEPARTMENT;

-- 7. WHAT IS THE DISTRIBUTION OF JOB TITLES ACROSS COMPANY?
SELECT JOBTITLE, COUNT(*) AS COUNT 
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY JOBTITLE
ORDER BY JOBTITLE DESC;

-- 8. WHICH DEPARTMENT HAS THE HIGHEST TURNOVER RATE?
SELECT DEPARTMENT,
	TOTAL_COUNT,
    TERMINATED_COUNT,
    TERMINATED_COUNT/TOTAL_COUNT AS TERMINATION_RATE
FROM (
	SELECT DEPARTMENT,
    COUNT(*) AS TOTAL_COUNT,
    SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNT
    FROM HR
    WHERE AGE >= 18
    GROUP BY DEPARTMENT
    ) AS SUBQUERY
ORDER BY TERMINATION_RATE DESC;

-- 9. WHAT IS THE DISTRIBUTION OF EMPLOYEES ACROSS LOCATIONS BY CITY AND STATE?
SELECT LOCATION_STATE, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE IS NULL
GROUP BY LOCATION_STATE
ORDER BY COUNT DESC;

-- 10. HOW HAS THE COMPANY'S EMPLOYEE COUNT CHANGED OVER TIME BASED ON HIRE AND TERM DATES?
SELECT
	YEAR,
    HIRES,
    TERMINATIONS,
    HIRES - TERMINATIONS AS NET_CHANGE,
    ROUND((HIRES - TERMINATIONS)/HIRES * 100, 2) AS NET_CHANGE_PERCENT
FROM(
	SELECT YEAR(HIRE_DATE) AS YEAR, 
    COUNT(*) AS HIRES,
    SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
    FROM HR
    WHERE AGE >=18
    GROUP BY YEAR(HIRE_DATE)
    ) AS SUBQUERY
ORDER BY YEAR ASC;

-- 11. WHAT IS THE TENURE DISTRIBUTION FOR EACH DEPARTMENT?
SELECT DEPARTMENT, ROUND(AVG(DATEDIFF(TERMDATE, HIRE_DATE)/365),0) AS AVG_TENURE
FROM HR
WHERE TERMDATE <=CURDATE() AND TERMDATE IS NOT NULL AND AGE >= 18
GROUP BY DEPARTMENT;